#!/usr/bin/env bats
load helpers/bats-helper.bash

setup() {
  cd "${REPO_ROOT}" || return
}

strip() {
  run bash -c 'printf "%s" "$1" | scripts/strip-pr-footer.sh' _ "$1"
}

@test "strip-pr-footer is executable" {
  [ -x scripts/strip-pr-footer.sh ]
}

@test "strip-pr-footer removes the cloud session footer" {
  strip $'## Summary\n\nText.\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_01AbC)_'
  [ "${status}" -eq 0 ]
  [ "${output}" = $'## Summary\n\nText.' ]
}

@test "strip-pr-footer removes the generated-with line and session link" {
  strip $'Body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_01AbC\n'
  [ "${status}" -eq 0 ]
  [ "${output}" = "Body." ]
}

@test "strip-pr-footer removes stacked footers" {
  strip $'Body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_01AbC)_\n'
  [ "${status}" -eq 0 ]
  [ "${output}" = "Body." ]
}

@test "strip-pr-footer keeps CRLF bodies intact apart from the footer" {
  strip $'Line one\r\nLine two\r\n\r\n---\r\n_Generated by [Claude Code](https://claude.ai/code/session_01AbC)_\r\n'
  [ "${status}" -eq 0 ]
  [ "${output}" = $'Line one\r\nLine two\r' ]
}

@test "strip-pr-footer leaves a body without the footer unchanged" {
  local body=$'## Summary\n\nMentions Claude Code in the text.\n\n---\nA closing note.'
  strip "${body}"
  [ "${status}" -eq 0 ]
  [ "${output}" = "${body}" ]
}

@test "strip-pr-footer keeps attribution lines that are not at the end" {
  local body=$'_Generated by [Claude Code](https://claude.ai/code/session_01AbC)_\n\nReal content.'
  strip "${body}"
  [ "${status}" -eq 0 ]
  [ "${output}" = "${body}" ]
}

@test "strip-pr-footer accepts an empty body" {
  strip ""
  [ "${status}" -eq 0 ]
  [ -z "${output}" ]
}

@test "pr-footer workflow runs the script on the base branch only" {
  local workflow=".github/workflows/pr-footer.yml"
  grep -Fq -- "pull_request_target:" "${workflow}"
  grep -Fq -- "types: [opened, edited]" "${workflow}"
  grep -Fq -- "pull-requests: write" "${workflow}"
  grep -Fq -- "scripts/strip-pr-footer.sh" "${workflow}"
  grep -Fq -- 'PR_BODY: ${{ github.event.pull_request.body }}' "${workflow}"
  ! grep -Fq -- "ref: \${{ github.event.pull_request.head" "${workflow}"
  ! grep -Eq -- 'run:.*\$\{\{ *github\.event\.pull_request\.body' "${workflow}"
}
