#!/usr/bin/env bash
# Shared Noble backport defaults and path helpers. Source this file.
set -euo pipefail

NODE_UNDICI_DEBIAN_VERSION="${NODE_UNDICI_DEBIAN_VERSION:-7.3.0+dfsg1+~cs24.12.11-1}"
NODE_UNDICI_NOBLE_VERSION="${NODE_UNDICI_NOBLE_VERSION:-7.3.0+dfsg1+~cs24.12.11-1~ubuntu24.04.2}"
OCSERV_DEBIAN_VERSION="${OCSERV_DEBIAN_VERSION:-1.5.0-1}"
OCSERV_NOBLE_VERSION="${OCSERV_NOBLE_VERSION:-1.5.0-1~ubuntu24.04.1}"
TARGET_DISTRIBUTION="${TARGET_DISTRIBUTION:-noble}"
TARGET_ARCH="${TARGET_ARCH:-amd64}"

export NODE_UNDICI_DEBIAN_VERSION NODE_UNDICI_NOBLE_VERSION
export OCSERV_DEBIAN_VERSION OCSERV_NOBLE_VERSION
export TARGET_DISTRIBUTION TARGET_ARCH

[[ "${TARGET_DISTRIBUTION}" == "noble" ]] || die "TARGET_DISTRIBUTION must be noble for Noble scripts"
[[ "${TARGET_ARCH}" =~ ^[A-Za-z0-9][A-Za-z0-9+._-]*$ ]] || die "bad TARGET_ARCH: ${TARGET_ARCH}"

NOBLE_SBUILD_CHROOT="${TARGET_DISTRIBUTION}-${TARGET_ARCH}"
export NOBLE_SBUILD_CHROOT

NOBLE_BUILD_ROOT="${REPO_ROOT}/build/noble/${TARGET_ARCH}"
NOBLE_REPO_DIR="${NOBLE_BUILD_ROOT}/repo"
export NOBLE_BUILD_ROOT NOBLE_REPO_DIR

noble_package_vars() {
  local package="$1"
  case "${package}" in
    node-undici)
      PKG_SOURCE="node-undici"
      PKG_DEBIAN_VERSION="${NODE_UNDICI_DEBIAN_VERSION}"
      PKG_NOBLE_VERSION="${NODE_UNDICI_NOBLE_VERSION}"
      ;;
    ocserv)
      PKG_SOURCE="ocserv"
      PKG_DEBIAN_VERSION="${OCSERV_DEBIAN_VERSION}"
      PKG_NOBLE_VERSION="${OCSERV_NOBLE_VERSION}"
      ;;
    *)
      die "usage: ${0##*/} node-undici|ocserv"
      ;;
  esac

  PKG_UPSTREAM_VERSION="${PKG_DEBIAN_VERSION%-*}"
  PKG_SOURCE_ROOT="${NOBLE_BUILD_ROOT}/source/${PKG_SOURCE}"
  PKG_SOURCE_TREE="${PKG_SOURCE_ROOT}/${PKG_SOURCE}-${PKG_UPSTREAM_VERSION}"
  PKG_BINARY_DIR="${NOBLE_BUILD_ROOT}/binary/${PKG_SOURCE}"
  PKG_LOCK_TSV="${REPO_ROOT}/source-lock/${PKG_SOURCE}/${PKG_DEBIAN_VERSION}.lock.tsv"

  export PKG_SOURCE PKG_DEBIAN_VERSION PKG_NOBLE_VERSION PKG_UPSTREAM_VERSION
  export PKG_SOURCE_ROOT PKG_SOURCE_TREE PKG_BINARY_DIR PKG_LOCK_TSV
}
