#!/usr/bin/env bash
# Remove the Claude Code attribution block from the end of a pull request
# body. Reads the body on stdin and writes it back without the block.
#
# Usage: strip-pr-footer.sh < body > stripped
#
# Only trailing lines are removed, and only these:
#   _Generated by [Claude Code](...)_
#   🤖 Generated with [Claude Code](...)
#   https://claude.ai/code/session_...
# plus the "---" rule and blank lines around them. A trailing "---" with no
# attribution after it is kept. Line endings (LF or CRLF) are preserved.
set -euo pipefail

footer_re='^(_Generated by \[Claude Code\]\([^)]*\)_|🤖 Generated with \[Claude Code\]\([^)]*\)|https://claude\.ai/code/session_[A-Za-z0-9_]+)$'

mapfile -t lines

# Line without a trailing CR, for matching.
line_at() {
  local line="${lines[$1]}"
  printf '%s' "${line%$'\r'}"
}

n="${#lines[@]}"
trim_blank() {
  while ((n > 0)) && [[ -z "$(line_at $((n - 1)))" ]]; do
    n=$((n - 1))
  done
}

end="${n}"
removed=0
trim_blank
while ((n > 0)); do
  last="$(line_at $((n - 1)))"
  if [[ "${last}" =~ ${footer_re} ]]; then
    removed=1
  elif ((removed)) && [[ "${last}" == "---" ]]; then
    :
  else
    break
  fi
  n=$((n - 1))
  trim_blank
done

if ((!removed)); then
  n="${end}"
fi
if ((n > 0)); then
  printf '%s\n' "${lines[@]:0:n}"
fi
